// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function parseDataJson(json) {
  return /* record */[
          /* full_name */Json_decode.field("full_name", Json_decode.string, json),
          /* stargazers_count */Json_decode.field("stargazers_count", Json_decode.$$int, json),
          /* html_url */Json_decode.field("html_url", Json_decode.string, json)
        ];
}

function parseDataResponseJson(json) {
  return Json_decode.field("items", (function (param) {
                return Json_decode.array(parseDataJson, param);
              }), json);
}

var githubSearchUrl = "https://api.github.com/search/repositories?q=topic%3Areasonml&type=Repositories";

function fetchTheData() {
  return fetch(githubSearchUrl).then((function (prim) {
                  return prim.text();
                })).then((function (jsonText) {
                return Promise.resolve(parseDataResponseJson(JSON.parse(jsonText)));
              }));
}

exports.parseDataJson = parseDataJson;
exports.parseDataResponseJson = parseDataResponseJson;
exports.githubSearchUrl = githubSearchUrl;
exports.fetchTheData = fetchTheData;
/* No side effect */
