// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var FetchData$ReactTemplate = require("./FetchData.bs.js");
var FetchDataItem$ReactTemplate = require("./FetchDataItem.bs.js");

var component = ReasonReact.reducerComponent("Fetch");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              FetchData$ReactTemplate.fetchTheData(/* () */0).then((function (result) {
                      Curry._1(self[/* send */3], /* Loaded */[result]);
                      return Promise.resolve(/* () */0);
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* githubData */0];
              var githubDataItem = match !== undefined ? $$Array.map((function (data) {
                        return ReasonReact.element(data[/* full_name */0], undefined, FetchDataItem$ReactTemplate.make(data, /* array */[]));
                      }), match) : "Loading";
              return React.createElement("div", undefined, React.createElement("h1", undefined, "Reason Projects from GitHub"), githubDataItem);
            }),
          /* initialState */(function () {
              return /* record */[/* githubData */undefined];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* githubData */action[0]]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
